import React from 'react';

const CreativePanel = ({ 
    setActiveTab, 
    generateCreativeContent, 
    generateImage,
    isThinking, 
    isImageGenerating,
    creativeOutput,
    settings,
    userInput,
    generatedImage,
    handleCodeExecution // optional prop
}) => {
  
  const outputText = typeof creativeOutput === 'string' ? creativeOutput : '';
  const isCodeSnippet = outputText.includes('```');

  return (
    <div className="creative-panel">
      <div className="creative-header">
        <h3>Creative Generation</h3>
        <button
          className="back-button"
          onClick={() => setActiveTab("chat")}
        >
          <i className="icon-arrow-left"></i> Back to Chat
        </button>
      </div>
      <div className="creative-description">
        <p>
          Explore AION's creative side! I can generate poems, code snippets, and more.
        </p>
      </div>
      <div className="creative-actions">
        <button
          className="creative-action-button"
          onClick={() => generateCreativeContent("poem")}
          disabled={isThinking || isImageGenerating}
        >
          Generate Poem
        </button>
        <button
          className="creative-action-button"
          onClick={() => generateCreativeContent("code")}
          disabled={isThinking || isImageGenerating}
        >
          Generate Code Snippet
        </button>
        <button
          className="creative-action-button"
          onClick={generateImage}
          disabled={isThinking || isImageGenerating || !settings.enableImageGeneration || !userInput.trim()}
        >
          {isImageGenerating ? 'Generating...' : 'Generate Image'}
        </button>
      </div>
      {creativeOutput && (
        <div className="creative-output-display">
          <h4>Generated Content:</h4>
          <pre className="creative-output">{creativeOutput}</pre>
          {/* NEW: Code Execution Button (only render if handler provided) */}
          {isCodeSnippet && typeof handleCodeExecution === 'function' && (
            <button
              className="creative-action-button run-code"
              onClick={() => handleCodeExecution(creativeOutput)}
              disabled={isThinking}
            >
              Run Code (Sandbox Simulation)
            </button>
          )}
        </div>
      )}
      {settings.enableImageGeneration && (
        <div className="image-generation-container">
          <h4>Generated Image:</h4>
          <div className="image-placeholder">
            {isImageGenerating ? (
              <div className="spinner-container">
                <div className="spinner"></div>
                <p>Generating image...</p>
              </div>
            ) : generatedImage ? (
              <img src={generatedImage} alt="Generated by AION" />
            ) : (
              <p>Enter a description in the chat input and click "Generate Image".</p>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default CreativePanel;